CUDA_VISIBLE_DEVICES=3 python -m domainbed.scripts.sweep launch\
       --data_dir=./domainbed/data/ \
       --output_dir=./train_output \
       --command_launcher local\
       --algorithms CAG1 \
       --datasets DomainNet \
       --n_hparams_from 0\
       --n_hparams 15\
       --n_trials 20\
       --skip_confirmation \
       --wandb \
       --single_test_envs